# Generated by Django 5.1 on 2024-10-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_showcaseofinstrumentst_type_of_instruments_showcase'),
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.instrumentscatalog'),
        ),
    ]
