# Generated by Django 5.1 on 2024-09-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_instruments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentsCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('model', models.CharField(max_length=100)),
                ('availability', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type_of_instruments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
        ),
    ]
