# Generated by Django 5.1 on 2024-09-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentscatalog',
            options={'ordering': ['title']},
        ),
    ]
