# Generated by Django 5.1 on 2024-09-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseOfInstrumentst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('type_of_goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
        ),
    ]
