# Generated by Django 5.1 on 2024-09-19 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_showcaseofinstrumentst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcaseofinstrumentst',
            name='type_of_goods',
        ),
        migrations.AddField(
            model_name='instrumentscatalog',
            name='type_of_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.showcaseofinstrumentst'),
        ),
    ]
