# Generated by Django 5.1 on 2024-09-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_showcaseofinstrumentst_type_of_goods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseofinstrumentst',
            name='type_of_instruments_showcase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
